-- ============================================================
-- TalaKlase — RBAC Migration
-- Run once against talaklasedb
-- ============================================================

-- 1. Add sectionID to assign_subject
-- (allows an instructor assignment to be scoped to a specific section)
ALTER TABLE `assign_subject`
  ADD COLUMN `sectionID` int(11) DEFAULT NULL AFTER `course_id`,
  ADD CONSTRAINT `assign_subject_ibfk_4`
    FOREIGN KEY (`sectionID`) REFERENCES `section` (`sectionID`) ON DELETE SET NULL,
  ADD UNIQUE KEY `uq_assignment` (`inst_id`, `sub_id`, `sectionID`);

-- 2. Archive support on instructor
ALTER TABLE `instructor`
  ADD COLUMN `is_archived`  tinyint(1)   NOT NULL DEFAULT 0   AFTER `dept_id`,
  ADD COLUMN `archived_at`  datetime     DEFAULT NULL,
  ADD COLUMN `archived_by`  int(11)      DEFAULT NULL;

-- 3. Users table (login accounts)
CREATE TABLE `users` (
  `id`            int(11)      NOT NULL AUTO_INCREMENT,
  `name`          varchar(150) NOT NULL,
  `username`      varchar(50)  NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role`          enum('admin','instructor','viewer') NOT NULL DEFAULT 'viewer',
  `inst_id`       int(11)      DEFAULT NULL
    COMMENT 'FK to instructor; only set when role = instructor',
  `is_active`     tinyint(1)   NOT NULL DEFAULT 1,
  `created_at`    datetime     NOT NULL DEFAULT current_timestamp(),
  `updated_at`    datetime     DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_username` (`username`),
  KEY `inst_id` (`inst_id`),
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`inst_id`) REFERENCES `instructor` (`inst_id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- 4. Seed a default admin account
--    IMPORTANT: replace the hash below with the real one generated by:
--    php -r "echo password_hash('Admin@2025', PASSWORD_BCRYPT);"
INSERT INTO `users` (`name`, `username`, `password_hash`, `role`)
VALUES (
  'System Admin',
  'admin',
  '$2y$12$0DJk9J0CZOgy7/ROY9giH..lQHt9GWWbAJy/JH27ikECQGmFoDfmy',
  'admin'
);